const state={all:[],filtered:[]};
function parseCSV(text){const lines=text.trim().split(/\r?\n/);return lines.map(line=>{const out=[];let cell="",quoted=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'&&quoted&&line[i+1]==='"'){cell+='"';i++;}else if(c==='"'){quoted=!quoted;}else if(c===','&&!quoted){out.push(cell);cell="";}else cell+=c;}out.push(cell);return out;});}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function monthKey(date){return date.slice(0,7)}
function monthLabel(key){return new Date(`${key}-01T00:00:00`).toLocaleDateString('id-ID',{month:'short',year:'numeric'});}
function loadData(text){const [head,...lines]=parseCSV(text);state.all=lines.filter(r=>r.length>=8&&r[0]).map(r=>Object.fromEntries(head.map((h,i)=>[h,r[i]??''])));const months=[...new Set(state.all.map(r=>monthKey(r.Tanggal)))].sort();const statuses=[...new Set(state.all.map(r=>r['Status Pekerjaan']))].sort();document.querySelector('#month').innerHTML='<option value="">Semua bulan</option>'+months.map(m=>`<option value="${m}">${monthLabel(m)}</option>`).join('');document.querySelector('#status').innerHTML='<option value="">Semua status</option>'+statuses.map(s=>`<option>${escapeHtml(s)}</option>`).join('');document.querySelector('#updated').textContent=`${state.all.length} catatan dimuat`;render();}
function drawBars(target,items,labelFn){const node=document.querySelector(target);if(!items.length){node.innerHTML='<span class="bar-label">Tidak ada data</span>';return;}const max=Math.max(...items.map(x=>x[1]),1);node.innerHTML=items.map(([k,v])=>`<div class="bar-row"><span class="bar-label" title="${escapeHtml(labelFn(k))}">${escapeHtml(labelFn(k))}</span><div class="track"><div class="fill" style="width:${Math.max(v/max*100,2)}%"></div></div><span class="bar-value">${v}</span></div>`).join('');}
function render(){const month=document.querySelector('#month').value,status=document.querySelector('#status').value;const data=state.all.filter(r=>(!month||monthKey(r.Tanggal)===month)&&(!status||r['Status Pekerjaan']===status));state.filtered=data;document.querySelector('#total').textContent=data.length;document.querySelector('#aog').textContent=data.filter(r=>r['Status Pesawat']==='AOG').length;const hrs=data.map(r=>Number(r['Durasi (jam)'])).filter(Number.isFinite);document.querySelector('#duration').textContent=hrs.length?(hrs.reduce((a,b)=>a+b,0)/hrs.length).toFixed(1)+' jam':'—';document.querySelector('#aircraft').textContent=new Set(data.map(r=>r['Registrasi Demo'])).size;const months={};const statuses={};for(const r of data){months[monthKey(r.Tanggal)]=(months[monthKey(r.Tanggal)]||0)+1;statuses[r['Status Pekerjaan']]=(statuses[r['Status Pekerjaan']]||0)+1;}drawBars('#monthly',Object.entries(months).sort(([a],[b])=>a.localeCompare(b)),monthLabel);drawBars('#statuses',Object.entries(statuses).sort((a,b)=>b[1]-a[1]),x=>x);document.querySelector('#rows').innerHTML=data.slice().sort((a,b)=>b.Tanggal.localeCompare(a.Tanggal)).map(r=>{const s=r['Status Pekerjaan'];const cl=s==='AOG'?'aog':s==='CLOSED'?'closed':s.startsWith('WTG')?'wait':'';return `<tr><td>${escapeHtml(r.Tanggal)}</td><td>${escapeHtml(r['Registrasi Demo'])}</td><td>${escapeHtml(r.Stasiun)}</td><td>${escapeHtml(r.Kategori)}</td><td>${escapeHtml(r['Deskripsi Defect'])}</td><td><span class="pill ${cl}">${escapeHtml(s)}</span></td><td>${escapeHtml(r['Durasi (jam)'])}</td></tr>`;}).join('');document.querySelector('#count-note').textContent=`Menampilkan ${data.length} catatan`;}
document.querySelector('#month').addEventListener('change',render);document.querySelector('#status').addEventListener('change',render);document.querySelector('#reset').addEventListener('click',()=>{document.querySelector('#month').value='';document.querySelector('#status').value='';render();});
fetch('./data.csv').then(r=>{if(!r.ok)throw new Error('CSV tidak ditemukan');return r.text();}).then(loadData).catch(()=>{document.querySelector('#updated').textContent='Data belum dimuat';document.querySelector('#rows').innerHTML='<tr><td colspan="7">Jalankan website melalui server lokal sesuai petunjuk README.md, lalu muat ulang halaman.</td></tr>';});
