const SHEET_ID='1ZVaSFBW8X_hdWGzOlRiQK1TWmULKJIch_xU45dRuPMs';
const GROUPS=['WG 10','WG 11','WG 12'];
const DATA_YEAR=2026;
const COLORS={'WG 10':'#2867c7','WG 11':'#e1a033','WG 12':'#7658b2'};
const state={dmi:[],readiness:{},errors:[]};
const monthNames=['Jan','Feb','Mar','Apr','Mei','Jun','Jul','Agu','Sep','Okt','Nov','Des'];
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function norm(s){return String(s??'').toLowerCase().replace(/[^a-z0-9]/g,'');}
function dateValue(v,f=''){if(v instanceof Date&&!Number.isNaN(v.valueOf()))return new Date(v.getFullYear(),v.getMonth(),v.getDate());if(typeof v==='string'){let m=v.match(/^Date\((\d{4}),(\d{1,2}),(\d{1,2})/);if(m)return new Date(Number(m[1]),Number(m[2]),Number(m[3]));if(/^\d{4}-\d{2}-\d{2}$/.test(v)){const d=new Date(`${v}T00:00:00`);if(!Number.isNaN(d.valueOf()))return d;}const d=new Date(v);if(!Number.isNaN(d.valueOf()))return new Date(d.getFullYear(),d.getMonth(),d.getDate());}if(typeof v==='number'&&Number.isFinite(v)&&v>30000&&v<100000){const d=new Date(Date.UTC(1899,11,30)+v*86400000);return new Date(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate());}if(f){const d=new Date(f);if(!Number.isNaN(d.valueOf()))return new Date(d.getFullYear(),d.getMonth(),d.getDate());}return null;}
function dateKey(d){return d?`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`:'';}
function dateMonth(d){return d?`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`:'';}
function cell(row,i){return row?.c?.[i]||null;}
function value(c){return c?.v??c?.f??'';}
function num(v){if(typeof v==='number')return Number.isFinite(v)?v:null;if(typeof v==='string'){let s=v.trim().replace('%','');if(!s)return null;let n=Number(s.replace(',','.'));return Number.isFinite(n)?n:null;}return null;}
function loadQuery(sheet,range,headers){return new Promise((resolve,reject)=>{const cb=`sheetCallback${Date.now()}${Math.floor(Math.random()*100000)}`;const script=document.createElement('script');let done=false;const finish=(err,result)=>{if(done)return;done=true;clearTimeout(timer);delete window[cb];script.remove();err?reject(err):resolve(result);};const timer=setTimeout(()=>finish(new Error(`Waktu akses habis untuk ${sheet}`)),25000);window[cb]=res=>{if(res?.status==='error'){finish(new Error(res.errors?.map(e=>e.detailed_message||e.message).join('; ')||`Google Sheets error: ${sheet}`));return;}if(!res?.table){finish(new Error(`Respons ${sheet} tidak berisi tabel`));return;}finish(null,res.table);};script.onerror=()=>finish(new Error(`Tidak dapat membaca tab ${sheet}`));const params=new URLSearchParams({sheet,range,headers:String(headers),tqx:`out:json;responseHandler:${cb}`});script.src=`https://docs.google.com/spreadsheets/d/${SHEET_ID}/gviz/tq?${params}`;document.head.appendChild(script);});}
function parseDmi(table,wg){const headers=table.cols.map(c=>norm(c.label||c.id));const idx=aliases=>headers.findIndex(h=>aliases.includes(h));const col={group:idx(['wg']),reg:idx(['acreg','acregistration']),defect:idx(['defectdescription','deffectdescription']),open:idx(['opendate']),mel:idx(['melcat']),close:idx(['closeddate']),station:idx(['staopen','stationopen']),pn:idx(['pndescription']),pnNumber:idx(['pnnnumber','pnnnumber','pnnumber']),restrict:idx(['restric','restrict']),remarks:idx(['remarks']),melRef:idx(['melref'])};const pick=(row,k)=>value(cell(row,col[k]));return table.rows.map(row=>{const r={wg,reg:String(pick(row,'reg')||'').trim(),defect:String(pick(row,'defect')||'').trim(),openDate:dateValue(pick(row,'open'),cell(row,col.open)?.f),closeDate:dateValue(pick(row,'close'),cell(row,col.close)?.f),mel:String(pick(row,'mel')||'').trim(),station:String(pick(row,'station')||'').trim(),pn:String(pick(row,'pn')||'').trim(),pnNumber:String(pick(row,'pnNumber')||'').trim(),restrict:String(pick(row,'restrict')||'').trim(),remarks:String(pick(row,'remarks')||'').trim(),melRef:String(pick(row,'melRef')||'').trim()};return r;}).filter(r=>/^PK-/i.test(r.reg)&&r.defect&&!/^a\/c reg$/i.test(r.reg));}
function parseReadiness(table,wg){const dateRowIndex=table.rows.findIndex(row=>{let matches=0;for(let i=1;i<=31;i++){const c=cell(row,i);const d=dateValue(value(c),c?.f);if(d&&d.getFullYear()===2026&&d.getMonth()===0)matches++;}return matches>=20;});if(dateRowIndex<0)return {wg,days:[]};const dateRow=table.rows[dateRowIndex];const dates=[];for(let i=1;i<=31;i++){const c=cell(dateRow,i);const d=dateValue(value(c),c?.f);if(!d||d.getFullYear()!==2026||d.getMonth()!==0)continue;const serv=num(value(cell(table.rows[dateRowIndex+6],i)));const aog=num(value(cell(table.rows[dateRowIndex+7],i)));const ready=num(value(cell(table.rows[dateRowIndex+8],i)));let pct=num(value(cell(table.rows[dateRowIndex+9],i)));if(pct!==null&&pct>1)pct=pct/100;if(pct===null&&serv>0&&ready!==null)pct=ready/serv;dates.push({date:d,serviceable:serv,aog,ready,pct});}return {wg,days:dates};}
async function loadSources(){const tasks=[];for(const wg of GROUPS){const n=wg.slice(-2);tasks.push(loadQuery(`DMI ${wg}`,'A8:V',1).then(t=>{state.dmi.push(...parseDmi(t,wg));}));tasks.push(loadQuery(`AC Readiness ${wg}`,'A1:AG12',0).then(t=>{state.readiness[wg]=parseReadiness(t,wg);}));}const results=await Promise.allSettled(tasks);results.forEach((r,i)=>{if(r.status==='rejected')state.errors.push(r.reason?.message||'Gagal membaca sumber');});state.dmi.sort((a,b)=>(b.openDate?.valueOf()||0)-(a.openDate?.valueOf()||0));fillFilters();render();const badge=document.querySelector('#load-status');if(state.errors.length){badge.className='load-status error';badge.innerHTML=`<span class="dot"></span> Sebagian data tidak tersedia (${state.errors.length})`;}else{badge.className='load-status ready';badge.innerHTML=`<span class="dot"></span> Data dimuat · ${state.dmi.length.toLocaleString('id-ID')} baris DMI`;}if(state.errors.length)document.querySelector('#data-note').textContent=`Catatan pemuatan: ${state.errors.join(' · ')}`;}
function groupChoice(){const v=document.querySelector('#wg').value;return v==='all'?GROUPS:[v];}
function selectedDmi(){return state.dmi.filter(r=>groupChoice().includes(r.wg));}
function openDmi(){return selectedDmi().filter(r=>!r.closeDate);}
function validAge(r){if(!r.openDate)return null;const now=new Date();now.setHours(0,0,0,0);const day=new Date(r.openDate);day.setHours(0,0,0,0);const diff=Math.floor((now-day)/86400000);return diff>=0&&diff<=3650?diff:null;}
function fillFilters(){const allMonths=new Set();for(const r of state.dmi){if(r.openDate?.getFullYear()===DATA_YEAR)allMonths.add(dateMonth(r.openDate));if(r.closeDate?.getFullYear()===DATA_YEAR)allMonths.add(dateMonth(r.closeDate));}const sorted=[...allMonths].sort();const month=document.querySelector('#month');month.innerHTML='<option value="all">Semua bulan 2026</option>'+sorted.map(m=>{const mm=Number(m.slice(5))-1;return `<option value="${m}">${monthNames[mm]} 2026</option>`;}).join('');if(sorted.length)month.value=sorted.at(-1);}
function filteredReadiness(){const groups=groupChoice();return groups.flatMap(g=>state.readiness[g]?.days||[]);}
function readinessSummary(){const groups=groupChoice();let ready=0,service=0;for(const g of groups)for(const d of state.readiness[g]?.days||[]){if(d.ready!==null&&d.serviceable>0){ready+=d.ready;service+=d.serviceable;}}return service?ready/service:null;}
function render(){const groups=groupChoice();const all=selectedDmi();const current=openDmi();const old=current.filter(r=>(validAge(r)??-1)>3);const month=document.querySelector('#month').value;const monthRows=all.filter(r=>month==='all'||dateMonth(r.openDate)===month||dateMonth(r.closeDate)===month);const monthOpened=monthRows.filter(r=>r.openDate&&r.openDate.getFullYear()===DATA_YEAR&&(month==='all'||dateMonth(r.openDate)===month)).length;const monthClosed=monthRows.filter(r=>r.closeDate&&r.closeDate.getFullYear()===DATA_YEAR&&(month==='all'||dateMonth(r.closeDate)===month)).length;document.querySelector('#open-total').textContent=current.length.toLocaleString('id-ID');document.querySelector('#over3-total').textContent=old.length.toLocaleString('id-ID');document.querySelector('#over3-share').textContent=current.length?`${(old.length/current.length*100).toFixed(1)}% dari DMI terbuka`:'berdasarkan tanggal buka';const label=month==='all'?'Jan–Des 2026':`${monthNames[Number(month.slice(5))-1]} 2026`;document.querySelector('#opened-month').textContent=monthOpened.toLocaleString('id-ID');document.querySelector('#closed-month').textContent=monthClosed.toLocaleString('id-ID');document.querySelector('#month-label-open').textContent=label;document.querySelector('#month-label-close').textContent=label;const avg=readinessSummary();document.querySelector('#readiness-average').textContent=avg===null?'—':`${(avg*100).toFixed(1)}%`;document.querySelector('#readiness-sub').textContent=groups.length===3?'rata-rata tertimbang · target >90%':`${groups[0]} · rata-rata tertimbang`;
 drawActivity(all);drawGroupBars(all);drawReadiness(groups);drawMel(current);drawStations(current);renderTable(current);
 const bad=current.filter(r=>!r.openDate||validAge(r)===null).length;document.querySelector('#data-note').textContent=`DMI terbuka dengan Open Date kosong/tidak wajar: ${bad}. Umur negatif atau tanggal terlalu jauh tidak dimasukkan ke hitungan >3 hari.`;}
function drawBars(id,items,color=COLORS['WG 10'],empty='Tidak ada data'){const root=document.querySelector(id);if(!items.length){root.innerHTML=`<div class="empty">${esc(empty)}</div>`;return;}const max=Math.max(...items.map(x=>x.value),1);root.innerHTML=items.map(x=>`<div class="bar-row"><span class="bar-label" title="${esc(x.label)}">${esc(x.label)}</span><div class="track"><div class="fill" style="width:${Math.max(x.value/max*100,1)}%;background:${x.color||color}"></div></div><span class="bar-value">${x.value.toLocaleString('id-ID')}</span></div>`).join('');}
function drawGroupBars(all){const items=groupChoice().map(wg=>({label:wg,value:all.filter(r=>r.wg===wg&&!r.closeDate).length,color:COLORS[wg]}));drawBars('#wg-chart',items);}
function drawMel(open){const c={};for(const r of open){const k=r.mel||'Kosong';c[k]=(c[k]||0)+1;}drawBars('#mel-chart',Object.entries(c).map(([label,value])=>({label,value})).sort((a,b)=>b.value-a.value));}
function drawStations(open){const c={};for(const r of open){const k=r.station||'Kosong';c[k]=(c[k]||0)+1;}drawBars('#station-chart',Object.entries(c).map(([label,value])=>({label,value})).sort((a,b)=>b.value-a.value).slice(0,10));}
function drawActivity(all){const monthly=new Map();for(let i=1;i<=12;i++)monthly.set(`${DATA_YEAR}-${String(i).padStart(2,'0')}`,{open:0,closed:0});for(const r of all){if(r.openDate?.getFullYear()===DATA_YEAR)monthly.get(dateMonth(r.openDate)).open++;if(r.closeDate?.getFullYear()===DATA_YEAR)monthly.get(dateMonth(r.closeDate)).closed++;}const values=[...monthly.entries()].map(([month,v])=>({month,...v}));const root=document.querySelector('#activity-chart');const W=740,H=220,L=36,R=12,T=10,B=30,PW=W-L-R,PH=H-T-B,max=Math.max(5,...values.map(v=>Math.max(v.open,v.closed)));const y=v=>T+PH-(v/max)*PH;const x=i=>L+i*PW/(values.length-1);let svg=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="DMI dibuka dan ditutup per bulan tahun 2026">`;for(let j=0;j<=4;j++){const val=max*j/4,yy=y(val);svg+=`<line class="grid-line" x1="${L}" y1="${yy}" x2="${W-R}" y2="${yy}"/><text class="axis-label" x="${L-8}" y="${yy+3}" text-anchor="end">${Math.round(val)}</text>`;}for(let i=0;i<values.length;i++){if(i%2===0||i===11)svg+=`<text class="axis-label" x="${x(i)}" y="${H-7}" text-anchor="middle">${monthNames[i]}</text>`;}for(const key of ['open','closed']){const col=key==='open'?'#2867c7':'#1e8a65';const points=values.map((v,i)=>`${x(i)},${y(v[key])}`).join(' ');svg+=`<polyline class="series-line" stroke="${col}" points="${points}"/>`;values.forEach((v,i)=>svg+=`<circle class="series-dot" cx="${x(i)}" cy="${y(v[key])}" r="3.2" fill="${col}"/>`);}svg+='</svg>';root.innerHTML=svg;}
function drawReadiness(groups){const series=groups.map(g=>({group:g,days:state.readiness[g]?.days||[],color:COLORS[g]})).filter(s=>s.days.length);const root=document.querySelector('#readiness-chart');if(!series.length){root.innerHTML='<div class="empty">Data readiness belum tersedia.</div>';document.querySelector('#readiness-legend').innerHTML='';document.querySelector('#readiness-summary').innerHTML='';return;}const dates=series[0].days.map(d=>d.date);const W=1100,H=230,L=48,R=20,T=12,B=32,PW=W-L-R,PH=H-T-B,yMin=.7,yMax=1.02;const x=i=>L+i*PW/Math.max(1,dates.length-1),y=v=>T+PH-(v-yMin)/(yMax-yMin)*PH;let svg=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Aircraft readiness harian Januari 2026">`;for(let p=.7;p<=1.0001;p+=.1){const yy=y(p);svg+=`<line class="grid-line" x1="${L}" y1="${yy}" x2="${W-R}" y2="${yy}"/><text class="axis-label" x="${L-8}" y="${yy+3}" text-anchor="end">${Math.round(p*100)}%</text>`;}const targetY=y(.9);svg+=`<line class="target-line" x1="${L}" y1="${targetY}" x2="${W-R}" y2="${targetY}"/>`;for(const s of series){const pts=s.days.map((d,i)=>d.pct===null?null:`${x(i)},${y(d.pct)}`).filter(Boolean);svg+=`<polyline class="series-line" stroke="${s.color}" points="${pts.join(' ')}"/>`;s.days.forEach((d,i)=>{if(d.pct!==null)svg+=`<circle class="series-dot" cx="${x(i)}" cy="${y(d.pct)}" r="2.5" fill="${s.color}"/>`;});}for(const i of [0,7,14,21,30])if(dates[i])svg+=`<text class="axis-label" x="${x(i)}" y="${H-7}" text-anchor="middle">${dates[i].getDate()} Jan</text>`;svg+='</svg>';root.innerHTML=svg;document.querySelector('#readiness-legend').innerHTML=series.map(s=>`<span><i class="key" style="background:${s.color}"></i>${esc(s.group)}</span>`).join('')+'<span><i class="key" style="background:#cf9834"></i>Target 90%</span>';document.querySelector('#readiness-summary').innerHTML=series.map(s=>{const vals=s.days.map(d=>d.pct).filter(v=>v!==null);const avg=vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null;const below=vals.filter(v=>v<.9).length;return `<div class="readiness-mini"><span>${esc(s.group)} · rata-rata ${avg===null?'—':(avg*100).toFixed(1)+'%'}</span><span>${below} hari &lt;90%</span></div>`;}).join('');}
function renderTable(open){const search=document.querySelector('#search').value.trim().toLowerCase();const onlyOld=document.querySelector('#over3').checked;let rows=open.filter(r=>{const age=validAge(r);if(onlyOld&&(age===null||age<=3))return false;if(search&&!`${r.reg} ${r.defect} ${r.pn} ${r.pnNumber} ${r.station}`.toLowerCase().includes(search))return false;return true;}).sort((a,b)=>(validAge(b)??-1)-(validAge(a)??-1));document.querySelector('#table-count').textContent=`${rows.length} dari ${open.length} DMI terbuka`;if(!rows.length){document.querySelector('#dmi-rows').innerHTML='<tr><td colspan="9" class="empty">Tidak ada DMI sesuai filter.</td></tr>';return;}document.querySelector('#dmi-rows').innerHTML=rows.map(r=>{const age=validAge(r);const restrict=/^yes$/i.test(r.restrict)?'<span class="restric yes">YES</span>':`<span class="restric">${esc(r.restrict||'—')}</span>`;return `<tr><td class="age">${age===null?'—':`${age} hari`}</td><td>${esc(r.wg)}</td><td><strong>${esc(r.reg)}</strong></td><td>${esc(r.openDate?dateKey(r.openDate):'Tanggal tidak tersedia')}</td><td>${esc(r.mel||'—')}</td><td>${esc(r.station||'—')}</td><td>${esc(r.defect)}</td><td>${esc(r.pn||'—')}</td><td>${restrict}</td></tr>`;}).join('');}
for(const id of ['wg','month'])document.querySelector(`#${id}`).addEventListener('change',render);document.querySelector('#search').addEventListener('input',()=>renderTable(openDmi()));document.querySelector('#over3').addEventListener('change',()=>renderTable(openDmi()));document.querySelector('#clear-search').addEventListener('click',()=>{document.querySelector('#search').value='';document.querySelector('#over3').checked=false;renderTable(openDmi());});
loadSources().catch(e=>{const b=document.querySelector('#load-status');b.className='load-status error';b.innerHTML='<span class="dot"></span> Gagal memuat spreadsheet';document.querySelector('#dmi-rows').innerHTML=`<tr><td colspan="9" class="empty">${esc(e.message||'Tidak dapat membaca spreadsheet.')}</td></tr>`;});




